#Network structure
version: '1.0'
name: caliper test
caliper:
  blockchain: fabric
clients:
  Admin@org1.example.com:
    client:
      organization: Org1
      credentialStore:
        path: /tmp/org1
        cryptoStore:
          path: /tmp/org1
      clientPrivateKey:
        path: >-
          /home/zj/test/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/priv_sk
      clientSignedCert:
        path: >-
          /home/zj/test/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/signcerts/Admin@org1.example.com-cert.pem
  Admin@org2.example.com:
    client:
      organization: Org2
      credentialStore:
        path: /tmp/org2
        cryptoStore:
          path: /tmp/org2
      clientPrivateKey:
        path: >-
          /home/zj/test/crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/priv_sk
      clientSignedCert:
        path: >-
          /home/zj/test/crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/signcerts/Admin@org2.example.com-cert.pem
channels:
  mychannel:
    created: true
    contracts:
      - id: mycc
        version: '1.0'
organizations:
  Org1:
    mspid: Org1MSP
    peers:
      - peer0.org1.example.com
    adminPrivateKey:
      path: >-
        /home/zj/test/crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp/keystore/priv_sk
    signedCert:
      path: >-
        /home/zj/test/crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/signcerts/Admin@org2.example.com-cert.pem
  Org2:
    mspid: Org2MSP
    peers:
      - peer0.org2.example.com
    adminPrivateKey:
      path: >-
        /home/zj/test/crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/keystore/priv_sk/priv_sk
    signedCert:
      path: >-
        /home/zj/test/crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp/signcerts/Admin@org2.example.com-cert.pem
orderers:
  orderer0.example.com:
    url: 'grpcs://116.62.238.255:7050'
    grpcOptions:
      ssl-target-name-override: orderer0.example.com
    tlsCACerts:
      path: >-
        /home/zj/test/crypto-config/ordererOrganizations/example.com/orderers/orderer0.example.com/msp/tlscacerts/tlsca.example.com-cert.pem
  orderer1.example.com:
    url: 'grpcs://116.62.238.255:8050'
    grpcOptions:
      ssl-target-name-override: orderer1.example.com
    tlsCACerts:
      path: >-
        /home/zj/test/crypto-config/ordererOrganizations/example.com/orderers/orderer1.example.com/msp/tlscacerts/tlsca.example.com-cert.pem
  orderer2.example.com:
    url: 'grpcs://118.31.10.159:7050'
    grpcOptions:
      ssl-target-name-override: orderer2.example.com
    tlsCACerts:
      path: >-
        /home/zj/test/crypto-config/ordererOrganizations/example.com/orderers/orderer2.example.com/msp/tlscacerts/tlsca.example.com-cert.pem
peers:
  peer0.org1.example.com:
    url: 'grpcs://116.62.238.255:7051'
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: >-
        /home/zj/test/crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp/tlscacerts/tlsca.org1.example.com-cert.pem
  peer0.org2.example.com:
    url: 'grpcs://118.31.10.159:7051'
    grpcOptions:
      ssl-target-name-override: peer0.org2.example.com
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: >-
        /home/zj/test/crypto-config/peerOrganizations/org2.example.com/peers/peer0.org2.example.com/msp/tlscacerts/tlsca.org2.example.com-cert.pem
